project:
  type: website
  output-dir: docs

website:
  title: "R For Molecular Medicine"
  navbar:
    background: "#0078bf"
    foreground: "#ffffff"
    left:
      - href: index.qmd
        text: Outline
      - text: Lessons
        menu:
          - text: Biostatistics and Epidemiology - Refresher
            href: bio-epi-refresher.qmd
          - text: Biostatistics and Epidemiology - Visualization
            href: bio-epi-visualization.qmd
          - text: Biostatistics and Epidemiology - Multiple testing
            href: bio-epi-multiple-testing.qmd
          - text: Biostatistics and Epidemiology - Advanced programming
            href: bio-epi-advanced.qmd
          - text: Biostatistics and Epidemiology - Statistical tests
            href: bio-epi-statistical-tests.qmd

format:
  html:
    theme: sandstone
    fontcolor: "#4b4b45"
    linkcolor: "#f08122"
    css: styles.css
    toc: true
    toc_depth: 4