project:
  type: website
  output-dir: docs

website:
  title: "R For Molecular Medicine"
  navbar:
    background: "#0078bf"
    foreground: "#ffffff"
    left:
      - icon: fab fa-github fa-lg
        href: http://github.com/zabore/mmedr
      - href: index.qmd
        text: Outline
      - text: Lessons
        menu:
          # - text: Why R is awesome
          #   href: r-awesome.qmd
          - text: Tools - Introduction
            href: tools-introduction.qmd
          - text: Tools - Install packages
            href: tools-install-packages.qmd
          - text: Tools - Loading data
            href: tools-loading-data.qmd
          - text: Tools - Reproducibility
            href: tools-reproducibility.qmd
          - text: Tools - Basic programming
            href: tools-basic-programming.qmd
          - text: Tools - Manipulate dataframes
            href: tools-manipulate-dataframes.qmd
          # - text: Tools - Descriptive statistics
          #   href: tools-descriptive-statistics.qmd
          - text: Tools - Put it all together
            href: tools-review-practice.qmd
          - text: Biostatistics and Epidemiology - Refresher
            href: bio-epi-refresher.qmd
          - text: Biostatistics and Epidemiology - Visualization
            href: bio-epi-visualization.qmd
          - text: Biostatistics and Epidemiology - Multiple testing
            href: bio-epi-multiple-testing.qmd
          - text: Biostatistics and Epidemiology - Advanced programming
            href: bio-epi-advanced.qmd
          - text: Biostatistics and Epidemiology - Statistical tests
            href: bio-epi-statistical-tests.qmd

format:
  html:
    theme: sandstone
    fontcolor: "#4b4b45"
    linkcolor: "#f08122"
    css: styles.css
    toc: true
    toc_depth: 3