---
title: ""
author: "Emily C. Zabor"
date: today
---

This website hosts R teaching materials for the Cleveland Clinic Molecular Medicine PhD program. The material will be split across 5 1-hour sessions as part of the Tools course, followed by 2 2-hour sessions as part of the Biostatistics and Epidemiology course. 

<!-- - [Why R is awesome](r-awesome.qmd) -->

## Tools course

### Session 1

- [Introduction to the tools](tools-introduction.qmd)

    - R
    - RStudio
    - Posit Workbench
    
- Using RStudio
    
- [Installing and loading R packages](tools-install-packages.qmd)

    - CRAN
    - Github
    - Bioconductor

### Session 2

- [Loading data](tools-loading-data.qmd)

    - .xlsx
    - .csv
    - Other formats
    - Variable names (janitor)
    
- [Reproducibility](tools-reproducibility.qmd)

    - RStudio projects
    - Project workflow and organization
    - {here} package

### Session 3

- [Basic programming](tools-basic-programming.qmd)

    - Assigning objects
    - Functions
    - Getting help
    - The pipe operator
    - Testing for equality
    - Indexing
    - Subsetting
    
### Session 4

- [Manipulate dataframes](tools-manipulate-dataframes.qmd)

    - The dplyr package
    - Rename columns
    - Add columns
    - Group a continuous variable
    - Recategorize a categorical variable
    - Sort by row

### Session 5

- [Put it all together](tools-review-practice.qmd)
    
## Biostatistics and Epidemiology

### Session 1

- [Refresher of the Tools course material](bio-epi-refresher.qmd)

- [Visualization](bio-epi-visualization.qmd) 

    - Scatterplot
    - Bar chart
    - Histogram
    - Line chart
    - Boxplot
    - Customization
    - Faceting
    - Saving plots
    
- [Descriptive statistics](bio-epi-descriptive-statistics.qmd)

    - One-way frequency table
    - Two-way contingency table
    - Summary statistics
    - Summary statistics by group
    - Creating publication-ready tables
    
### Session 2
    
- [Advanced programming](bio-epi-advanced.qmd)

    - Writing custom functions
    - For loops/apply/map

- [Statistical tests](bio-epi-statistical-tests.qmd)

    - Fisher's exact test
    - Chi-squared test
    - Wilcoxon rank sum test/Kruskal-Wallis test
    - T-test 
    - ANOVA
    - Wilcoxon signed rank test 
    - Paired t-test
    
- [Adjustment for multiple comparisons](bio-epi-multiple-testing.qmd)

